### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by lanling175** [ChristopherHaws/mc-xaero-map-spigot#1]

**Comment by ChristopherHaws** [comment]
All you need to do is install it on the server like any other plugin. There is no config since all the plugin does is one thing. When you connect to the world, Xaero's World Map should show that it is using the server to pick the correct map.

![image](https://user-images.githubusercontent.com/5934505/198704011-7022471f-77a1-44cc-a4b3-7c0711dc4a6a.png)

**Comment by lanling175** [comment]
Where do I put the Xaero's World Map plug-in? Is it also in the plug-in folder?Why did I release it and didn't respond?

**Comment by ChristopherHaws** [comment]
Yes, in the plugin folder like a standard plugin.

**Comment by lanling175** [comment]
![微信截图_20221102100711](https://user-images.githubusercontent.com/26915306/199382812-d4abe8da-1019-4749-907b-d9fb02ff5eba.png)
Error message, here is a screenshot.

**Comment by ChristopherHaws** [comment]
You cannot run fabric mods on spigot. This plugin does not make xaero maps run on the server. This plugin simply sends a packet to clients that are running xaeros so that their map selection is set by the server. Clients still need to run xaeros.

**Comment by lanling175** [comment]
I see. thank you！

**Comment by ChristopherHaws** [comment]
No problem. I haven't had a chance to detail exactly what the mod does in the description. Hope the mod helps you out. It's really only needed if you are running multiple servers behind a proxy such as velocity. This is the only server side feature that Xaero's World Map currently provides.
